theme: jekyll-theme-leap-day
title: "Diskriminierung und Missmanagement bei der ILB"
description: "Diese Website beleuchtet die Herausforderungen und Ungerechtigkeiten, denen ich als Mitarbeiter der ILB begegnet bin. Der Fokus liegt auf den unprofessionellen Handlungen der Personalabteilung und der mangelnden klaren und transparenten Kommunikation. Durch die Dokumentation und Analyse der Vorfälle möchte ich auf die Missstände aufmerksam machen und für Gerechtigkeit sorgen."




