title: "Diskriminierung und Missmanagement bei der ILB"
description: "Diese Website beleuchtet die Herausforderungen und Ungerechtigkeiten, denen ich als Mitarbeiter der ILB begegnet bin. Der Fokus liegt auf den unprofessionellen Handlungen der Personalabteilung und der mangelnden klaren und transparenten Kommunikation. Die Personalabteilung hat Wochen verstreichen lassen, um mir letztendlich die Vertragsangebot zur체ckzuziehen und mich erneut freizustellen. Dabei haben sie versucht, mich zu diskreditieren, indem sie mir falsches Verhalten und andere unbegr체ndete Vorw체rfe gemacht haben. Mein Ziel ist es, Gerechtigkeit zu erlangen und auf die Missst채nde aufmerksam zu machen."
theme: jekyll-theme-leap-day

google_analytics: UA-XXXXXX-Y



